'''
Reads data in from the feature file generated by download_data.py 
'''

import os
import sys
import tensorflow as tf
import numpy as np
import json
import math
import constants as const

# parameter used when parsing and serializing data
weekCount = const.WEEK_COUNT
dataPerDay = const.DATA_PER_DAY

def readOne(filename):
    # first construct a queue containing a list of filenames.
    # this lets a user split up the dataset in multiple files to keep size down
    filename_queue = tf.train.string_input_producer([filename], num_epochs=None)

    reader = tf.TFRecordReader()
    # One can read a single serialized example from a filename
    # serialized_example is a Tensor of type string.
    _, serialized_example = reader.read(filename_queue)

    # The serialized example is converted back to actual values.
    # One needs to describe the format of the objects to be returned
    features = tf.parse_single_example(serialized_example, features={
        # We know the length of both fields. If not the
        # tf.VarLenFeature could be used
        'label': tf.FixedLenFeature([2], tf.int64),
        'data': tf.FixedLenFeature([weekCount, dataPerDay, 1], tf.float32)
    })
    # now return the converted data
    label = features['label']
    data = features['data']
    return data, label

